### ISSUE TITLE
Bower don't update this package

### ISSUE THREAD

**Issue by FedeG** [lelylan/device-directive-ng#110]
@andreareginato Dockerhub send error events when build the devices-dashboard-ng ([docker hub detail (required docker lelylanlab hub access)](https://hub.docker.com/r/lelylanlab/devices-dashboard-ng/builds/bqf4cmnrnlyzofjqumfnemk/)).

In this pull requests https://github.com/lelylan/device-directive-ng/pull/106, i change device-directive-ng version but bower don't update this package.

Docker hub error event:
```bash
bower device-directive-ng#~0.2.9     ENORESTARGET No tag found that was able to satisfy ~0.2.9

Additional error details:
Available versions in https://github.com/lelylan/device-directive-ng.git: 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.0, 0.2.0-beta.4, 0.2.0-beta.3, 0.2.0-beta.2, 0.2.0-beta.1, 0.2.0-beta
```

@andreareginato, can you update this package?

**Comment by andreareginato** [comment]
Package updated.
